#!/bin/dash

purple=#828dd1
darkpurple=#6c77bb
black=#1e222a
green=#7eca9c
darkgreen=#6db589
white=#abb2bf
grey=#282c34
blue=#7aa2f7
darkblue=#80a0c1
red=#d47d85
darkred=#E06C75
darkblue=#668ee3
yellow=#e5c07b
darkyellow=#d1ab64
